// generated by `sqlx migrate build-script`
fn main() {
    prost_build::compile_protos(&[
        "proto/message.proto",
        "proto/protocol.proto"
    ], &["proto/"])
    .unwrap();
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=src/storage/sqlite/migrations");
}
